//
//  AppState.swift
//  Taqvo
//
//  Generated by Assistant on 10/17/25
//

import Foundation
import Combine

// Global music provider selection
enum MusicProvider: String, CaseIterable {
    case spotify
    case apple
}

final class AppState: ObservableObject {
    @Published var hasCompletedOnboarding: Bool = false

    // Permissions state
    @Published var locationAuthorized: Bool = false
    @Published var motionAuthorized: Bool = false
    @Published var healthAuthorized: Bool = false // optional per PRD
    @Published var backgroundTrackingEnabled: Bool = false // authorizedAlways

    var allRequiredPermissionsGranted: Bool {
        locationAuthorized && motionAuthorized
    }
}