//
//  AppState.swift
//  Taqvo
//
//  Generated by Assistant on 10/17/25
//

import Foundation
import Combine

// Global music provider selection
enum MusicProvider: String, CaseIterable {
    case spotify
    case apple
}

// Simple intent enums for Activity preselection
enum ActivityIntentType: String, CaseIterable { case walk, jog, run, ride }
enum GoalIntentType: String, CaseIterable { case none, time, distance }

final class AppState: ObservableObject {
    @Published var hasCompletedOnboarding: Bool = false

    // Permissions state
    @Published var locationAuthorized: Bool = false
    @Published var motionAuthorized: Bool = false
    @Published var healthAuthorized: Bool = false // optional per PRD
    @Published var backgroundTrackingEnabled: Bool = false // authorizedAlways

    // Navigation intents
    @Published var navigateToActivity: Bool = false

    // Activity preselection intents
    @Published var activityIntent: ActivityIntentType? = nil
    @Published var goalIntentType: GoalIntentType? = nil
    @Published var goalIntentSeconds: Double? = nil
    @Published var goalIntentMeters: Double? = nil

    // Challenge link context for the next activity/live view
    @Published var linkedChallengeTitle: String? = nil
    @Published var linkedChallengeIsPublic: Bool? = nil

    var allRequiredPermissionsGranted: Bool {
        locationAuthorized && motionAuthorized
    }
}