//
//  MainTabView.swift
//  Taqvo
//
//  Generated by Assistant on 10/17/25
//

import SwiftUI
import UIKit
import Charts

struct MainTabView: View {
    @State private var selectedTab: Tab = .activity

    enum Tab: Hashable {
        case feed, community, activity, insights, profile
    }

    var body: some View {
        TabView(selection: $selectedTab) {
            FeedView()
                .tabItem {
                    Label("Feed", systemImage: "list.bullet")
                }
                .tag(Tab.feed)

            CommunityView()
                .tabItem {
                    Label("Community", systemImage: "person.3")
                }
                .tag(Tab.community)

            ActivityView()
                .tabItem {
                    VStack {
                        Image(systemName: "figure.run")
                            .symbolEffect(.pulse, options: .repeating, value: selectedTab == .activity)
                        Text("Activity")
                    }
                }
                .tag(Tab.activity)

            InsightsView()
                .tabItem {
                    Label("Insights", systemImage: "chart.bar.fill")
                }
                .tag(Tab.insights)

            ProfileView()
                .tabItem {
                    Label("Profile", systemImage: "person.crop.circle")
                }
                .tag(Tab.profile)
        }
        .tint(.taqvoCTA)
        .background(Color.taqvoBackgroundDark)
    }
}

struct ActivityView: View {
    @State private var activityType: ActivityType = .run
    @State private var goal: Goal = .none
    @State private var navigateToLive: Bool = false
    @StateObject private var trackingVM = ActivityTrackingViewModel()

    @AppStorage("goalType") private var storedGoalType: String = Goal.none.rawValue
    @AppStorage("goalTimeSeconds") private var storedGoalTimeSeconds: Double = 30 * 60
    @AppStorage("goalDistanceMeters") private var storedGoalDistanceMeters: Double = 5000
    @AppStorage("autoEndOnGoal") private var storedAutoEndOnGoal: Bool = false

    @State private var timeMinutes: Int = 30
    @State private var distanceKilometers: Double = 5.0

    enum ActivityType: String, CaseIterable { case walk, jog, run }
    enum Goal: String, CaseIterable { case none, time, distance }

    var body: some View {
        NavigationStack {
            VStack(spacing: 20) {
                Text("Pre-Run Setup")
                    .font(.title2)
                    .foregroundColor(.taqvoTextDark)

                Picker("Type", selection: $activityType) {
                    ForEach(ActivityType.allCases, id: \.self) { t in
                        Text(t.rawValue.capitalized)
                    }
                }
                .pickerStyle(.segmented)

                Picker("Goal", selection: $goal) {
                    ForEach(Goal.allCases, id: \.self) { g in
                        Text(g.rawValue.capitalized)
                    }
                }
                .pickerStyle(.segmented)
                .onChange(of: goal) { new in
                    storedGoalType = new.rawValue
                }

                if goal == .time {
                    Stepper(value: $timeMinutes, in: 5...180, step: 5) {
                        Text("Time: \(timeMinutes) min")
                            .foregroundColor(.taqvoTextDark)
                    }
                    .onChange(of: timeMinutes) { new in
                        storedGoalTimeSeconds = Double(new * 60)
                    }
                } else if goal == .distance {
                    Stepper(value: $distanceKilometers, in: 1...42.2, step: 0.5) {
                        Text(String(format: "Distance: %.1f km", distanceKilometers))
                            .foregroundColor(.taqvoTextDark)
                    }
                    .onChange(of: distanceKilometers) { new in
                        storedGoalDistanceMeters = new * 1000.0
                    }
                }

                Toggle("Auto-end on goal", isOn: $storedAutoEndOnGoal)
                    .tint(.taqvoCTA)

                Button {
                    switch goal {
                    case .none:
                        trackingVM.setTimeGoal(nil)
                        trackingVM.setDistanceGoal(nil)
                    case .time:
                        trackingVM.setTimeGoal(Double(timeMinutes * 60))
                        trackingVM.setDistanceGoal(nil)
                    case .distance:
                        trackingVM.setDistanceGoal(distanceKilometers * 1000.0)
                        trackingVM.setTimeGoal(nil)
                    }
                    trackingVM.autoEndOnGoal = storedAutoEndOnGoal
                    navigateToLive = true
                } label: {
                    Text("Start")
                        .font(.headline)
                        .foregroundColor(.black)
                        .padding()
                        .frame(maxWidth: .infinity)
                        .background(Color.taqvoCTA)
                        .cornerRadius(16)
                }
                .padding(.top, 8)
            }
            .padding()
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color.taqvoBackgroundDark)
            .navigationTitle("Activity")
            .onAppear {
                goal = Goal(rawValue: storedGoalType) ?? .none
                timeMinutes = max(5, min(180, Int(storedGoalTimeSeconds / 60)))
                distanceKilometers = max(1.0, min(42.2, storedGoalDistanceMeters / 1000.0))
            }
            .navigationDestination(isPresented: $navigateToLive) {
                LiveActivityView()
                    .environmentObject(trackingVM)
            }
        }
    }
}

struct FeedView: View {
    @EnvironmentObject var store: ActivityStore

    var body: some View {
        NavigationStack {
            Group {
                if store.activities.isEmpty {
                    VStack(spacing: 12) {
                        Text("No activities yet")
                            .font(.title3)
                            .foregroundColor(.taqvoTextDark)
                        Text("Finish a run and Share to Feed from the summary.")
                            .font(.caption)
                            .foregroundColor(.taqvoAccentText)
                            .multilineTextAlignment(.center)
                    }
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else {
                    List {
                        ForEach(store.activities) { a in
                            NavigationLink(destination: ActivityDetailView(activity: a)) {
                                ActivityRow(activity: a)
                            }
                            .listRowBackground(Color.black.opacity(0.08))
                        }
                    }
                    .listStyle(.plain)
                }
            }
            .background(Color.taqvoBackgroundDark)
            .navigationTitle("Feed")
        }
    }
}

struct ActivityRow: View {
    let activity: FeedActivity

    private var paceString: String {
        ActivityTrackingViewModel.formattedPace(distanceMeters: activity.distanceMeters,
                                               durationSeconds: activity.durationSeconds)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            if let data = activity.photoPNG, let img = UIImage(data: data) {
                Image(uiImage: img)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .cornerRadius(12)
            } else if let data = activity.snapshotPNG, let img = UIImage(data: data) {
                Image(uiImage: img)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .cornerRadius(12)
            } else {
                MapRouteView(route: ActivityStore.clCoordinates(from: activity.route))
                    .frame(height: 180)
                    .cornerRadius(12)
            }

            HStack {
                Text(String(format: "%.2f km", activity.distanceMeters/1000.0))
                    .foregroundColor(.taqvoTextDark)
                    .font(.headline)
                Spacer()
                Text(ActivityTrackingViewModel.formattedDuration(activity.durationSeconds))
                    .foregroundColor(.taqvoTextDark)
                    .font(.headline)
                Spacer()
                Text(paceString)
                    .foregroundColor(.taqvoAccentText)
                    .font(.subheadline)
            }
            if let note = activity.note, !note.isEmpty {
                Text(note)
                    .foregroundColor(.taqvoTextDark)
                    .font(.body)
            }
            Text(activity.endDate.formatted(date: .abbreviated, time: .shortened))
                .foregroundColor(.taqvoAccentText)
                .font(.caption)
        }
        .padding(.vertical, 8)
    }
}

struct CommunityView: View {
    @EnvironmentObject var store: ActivityStore
    @EnvironmentObject var community: CommunityViewModel

    var body: some View {
        NavigationStack {
            List {
                Section("Challenges") {
                    ForEach(community.challenges) { ch in
                        NavigationLink(destination: ChallengeDetailView(challenge: ch)) {
                            VStack(alignment: .leading, spacing: 8) {
                                HStack {
                                    Text(ch.title)
                                        .font(.headline)
                                        .foregroundColor(.taqvoTextDark)
                                    Spacer()
                                    Button(community.challenges.first(where: { $0.id == ch.id })?.isJoined == true ? "Leave" : "Join") {
                                        community.toggleJoin(challengeID: ch.id)
                                        community.refreshProgress(from: store)
                                    }
                                    .buttonStyle(.bordered)
                                    .tint(.taqvoCTA)
                                }
                                Text(ch.detail)
                                    .font(.caption)
                                    .foregroundColor(.taqvoAccentText)
                                HStack {
                                    Text("Goal \(String(format: "%.0f km", ch.goalDistanceMeters/1000))")
                                        .font(.caption)
                                        .foregroundColor(.taqvoAccentText)
                                    Spacer()
                                    Text("\(ch.durationDays) days")
                                        .font(.caption)
                                        .foregroundColor(.taqvoAccentText)
                                }
                                ProgressView(value: (community.challenges.first(where: { $0.id == ch.id })?.progressFraction ?? ch.progressFraction)) {
                                    Text(String(format: "%.1f/%.1f km", (community.challenges.first(where: { $0.id == ch.id })?.progressMeters ?? ch.progressMeters)/1000.0, ch.goalDistanceMeters/1000.0))
                                        .foregroundColor(.taqvoTextDark)
                                        .font(.subheadline)
                                }
                                .tint(.taqvoCTA)
                            }
                            .padding(.vertical, 8)
                            .listRowBackground(Color.black.opacity(0.08))
                        }
                    }
                }

                Section("Leaderboard") {
                    ForEach(community.leaderboard) { e in
                        HStack {
                            Text("#\(e.rank)")
                                .foregroundColor(.taqvoAccentText)
                                .frame(width: 32)
                            Text(e.userName)
                                .foregroundColor(.taqvoTextDark)
                            Spacer()
                            Text(String(format: "%.1f km", e.totalDistanceMeters/1000.0))
                                .foregroundColor(.taqvoTextDark)
                                .font(.headline)
                        }
                        .padding(.vertical, 4)
                        .listRowBackground(Color.black.opacity(0.08))
                    }
                }
            }
            .listStyle(.grouped)
            .background(Color.taqvoBackgroundDark)
            .navigationTitle("Community")
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button {
                        community.load()
                        community.refreshProgress(from: store)
                    } label: {
                        Label("Reload", systemImage: "arrow.clockwise")
                    }
                }
            }
        }
        .onAppear {
            if community.challenges.isEmpty { community.load() }
            community.refreshProgress(from: store)
        }
    }
}

struct InsightsView: View {
    @EnvironmentObject var store: ActivityStore
    @State private var period: Period = .weekly

    enum Period: String, CaseIterable { case daily, weekly, monthly }

    private func km(_ meters: Double) -> String {
        String(format: "%.2f km", meters/1000.0)
    }

    private func paceMinPerKm(distanceMeters: Double, durationSeconds: Double) -> Double {
        guard distanceMeters > 1, durationSeconds > 0 else { return 0 }
        let secPerKm = durationSeconds / (distanceMeters / 1000.0)
        return secPerKm / 60.0
    }

    private func exportInsightsCSV(period: Period, weekly: [WeeklySummary], daily: [DailySummary], monthly: [MonthlySummary]) -> URL {
        var rows: [String] = ["date,total_km,total_seconds,avg_pace_min_per_km,longest_run_km,longest_run_seconds,run_count"]
        let df = ISO8601DateFormatter()
        switch period {
        case .weekly:
            for w in weekly {
                let avg = paceMinPerKm(distanceMeters: w.totalDistanceMeters, durationSeconds: w.totalDurationSeconds)
                rows.append("\(df.string(from: w.weekStart)),\(String(format: "%.2f", w.totalDistanceMeters/1000.0)),\(Int(w.totalDurationSeconds)),\(String(format: "%.2f", avg)),\(String(format: "%.2f", w.longestRunMeters/1000.0)),\(Int(w.longestRunDurationSeconds)),\(0)")
            }
        case .daily:
            for d in daily {
                let avg = paceMinPerKm(distanceMeters: d.totalDistanceMeters, durationSeconds: d.totalDurationSeconds)
                rows.append("\(df.string(from: d.dayStart)),\(String(format: "%.2f", d.totalDistanceMeters/1000.0)),\(Int(d.totalDurationSeconds)),\(String(format: "%.2f", avg)),\(String(format: "%.2f", d.longestRunMeters/1000.0)),\(Int(d.longestRunDurationSeconds)),\(d.runCount)")
            }
        case .monthly:
            for m in monthly {
                let avg = paceMinPerKm(distanceMeters: m.totalDistanceMeters, durationSeconds: m.totalDurationSeconds)
                rows.append("\(df.string(from: m.monthStart)),\(String(format: "%.2f", m.totalDistanceMeters/1000.0)),\(Int(m.totalDurationSeconds)),\(String(format: "%.2f", avg)),\(String(format: "%.2f", m.longestRunMeters/1000.0)),\(Int(m.longestRunDurationSeconds)),\(m.runCount)")
            }
        }
        let csv = rows.joined(separator: "\n")
        let filename = "taqvo-insights-\(period.rawValue)-\(Int(Date().timeIntervalSince1970)).csv"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        try? csv.data(using: .utf8)?.write(to: url)
        return url
    }

    var body: some View {
        NavigationStack {
            Group {
                let weekly = store.weeklySummaries()
                let daily = store.dailySummaries()
                let monthly = store.monthlySummaries()
                let allEmpty = weekly.isEmpty && daily.isEmpty && monthly.isEmpty

                if allEmpty {
                    VStack(spacing: 12) {
                        Text("No insights yet")
                            .font(.title3)
                            .foregroundColor(.taqvoTextDark)
                        Text("Share your runs to build insights across periods.")
                            .font(.caption)
                            .foregroundColor(.taqvoAccentText)
                            .multilineTextAlignment(.center)
                    }
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else {
                    VStack(spacing: 16) {
                        // Active streak metric
                        HStack {
                            Text("Streak")
                                .font(.caption)
                                .foregroundColor(.taqvoAccentText)
                            Spacer()
                            Text("\(store.activeDaysStreak()) days")
                                .font(.headline)
                                .foregroundColor(.taqvoTextDark)
                        }

                        Picker("Period", selection: $period) {
                            Text("Daily").tag(Period.daily)
                            Text("Weekly").tag(Period.weekly)
                            Text("Monthly").tag(Period.monthly)
                        }
                        .pickerStyle(.segmented)

                        // Distance chart
                        if period == .weekly {
                            Chart(weekly.prefix(8).reversed()) { w in
                                BarMark(
                                    x: .value("Week", w.weekStart),
                                    y: .value("Distance (km)", w.totalDistanceMeters/1000.0)
                                )
                                .foregroundStyle(Color.taqvoCTA)
                            }
                            .frame(height: 160)
                            .padding(.vertical, 4)
                            .background(Color.black.opacity(0.08))
                            .cornerRadius(12)
                        } else if period == .daily {
                            Chart(daily.prefix(14).reversed()) { d in
                                BarMark(
                                    x: .value("Day", d.dayStart),
                                    y: .value("Distance (km)", d.totalDistanceMeters/1000.0)
                                )
                                .foregroundStyle(Color.taqvoCTA)
                            }
                            .frame(height: 160)
                            .padding(.vertical, 4)
                            .background(Color.black.opacity(0.08))
                            .cornerRadius(12)
                        } else {
                            Chart(monthly.prefix(6).reversed()) { m in
                                BarMark(
                                    x: .value("Month", m.monthStart),
                                    y: .value("Distance (km)", m.totalDistanceMeters/1000.0)
                                )
                                .foregroundStyle(Color.taqvoCTA)
                            }
                            .frame(height: 160)
                            .padding(.vertical, 4)
                            .background(Color.black.opacity(0.08))
                            .cornerRadius(12)
                        }

                        // Pace trend chart
                        if period == .weekly {
                            Chart(weekly.prefix(8).reversed()) { w in
                                LineMark(
                                    x: .value("Week", w.weekStart),
                                    y: .value("Pace (min/km)", paceMinPerKm(distanceMeters: w.totalDistanceMeters, durationSeconds: w.totalDurationSeconds))
                                )
                                .foregroundStyle(Color.taqvoAccentText)
                            }
                            .frame(height: 120)
                            .background(Color.black.opacity(0.08))
                            .cornerRadius(12)
                        } else if period == .daily {
                            Chart(daily.prefix(14).reversed()) { d in
                                LineMark(
                                    x: .value("Day", d.dayStart),
                                    y: .value("Pace (min/km)", paceMinPerKm(distanceMeters: d.totalDistanceMeters, durationSeconds: d.totalDurationSeconds))
                                )
                                .foregroundStyle(Color.taqvoAccentText)
                            }
                            .frame(height: 120)
                            .background(Color.black.opacity(0.08))
                            .cornerRadius(12)
                        } else {
                            Chart(monthly.prefix(6).reversed()) { m in
                                LineMark(
                                    x: .value("Month", m.monthStart),
                                    y: .value("Pace (min/km)", paceMinPerKm(distanceMeters: m.totalDistanceMeters, durationSeconds: m.totalDurationSeconds))
                                )
                                .foregroundStyle(Color.taqvoAccentText)
                            }
                            .frame(height: 120)
                            .background(Color.black.opacity(0.08))
                            .cornerRadius(12)
                        }

                        // Cards list
                        if period == .weekly {
                            List(weekly) { w in
                                WeeklySummaryCard(summary: w)
                                    .listRowBackground(Color.black.opacity(0.08))
                            }
                            .listStyle(.plain)
                        } else if period == .daily {
                            List(daily) { d in
                                DailySummaryCard(summary: d)
                                    .listRowBackground(Color.black.opacity(0.08))
                            }
                            .listStyle(.plain)
                        } else {
                            List(monthly) { m in
                                MonthlySummaryCard(summary: m)
                                    .listRowBackground(Color.black.opacity(0.08))
                            }
                            .listStyle(.plain)
                        }
                    }
                }
            }
            .background(Color.taqvoBackgroundDark)
            .navigationTitle("Insights")
            .toolbar {
                let weekly = store.weeklySummaries()
                let daily = store.dailySummaries()
                let monthly = store.monthlySummaries()
                ToolbarItem(placement: .navigationBarTrailing) {
                    ShareLink(item: exportInsightsCSV(period: period, weekly: weekly, daily: daily, monthly: monthly)) {
                        Label("Share", systemImage: "square.and.arrow.up")
                    }
                }
            }
        }
    }
}

struct WeeklyBarChart: View {
    let weeks: [WeeklySummary]

    private var maxDistance: Double {
        weeks.map { $0.totalDistanceMeters }.max() ?? 1
    }

    var body: some View {
        GeometryReader { geo in
            HStack(alignment: .bottom, spacing: 8) {
                ForEach(weeks, id: \.id) { w in
                    let ratio = CGFloat(w.totalDistanceMeters / maxDistance)
                    VStack {
                        RoundedRectangle(cornerRadius: 6)
                            .fill(Color.taqvoCTA)
                            .frame(width: (geo.size.width - 8 * CGFloat(weeks.count - 1)) / CGFloat(weeks.count), height: max(12, geo.size.height * ratio))
                        Text(String(format: "%.0f km", w.totalDistanceMeters/1000.0))
                            .font(.caption2)
                            .foregroundColor(.taqvoAccentText)
                            .lineLimit(1)
                        Text(w.weekStart.formatted(.dateTime.month().day()))
                            .font(.caption2)
                            .foregroundColor(.taqvoAccentText)
                            .lineLimit(1)
                    }
                }
            }
        }
    }
}

struct WeeklySummaryCard: View {
    let summary: WeeklySummary

    private var rangeText: String {
        let cal = Calendar(identifier: .iso8601)
        let end = cal.date(byAdding: .day, value: 6, to: summary.weekStart) ?? summary.weekStart
        let startStr = summary.weekStart.formatted(date: .abbreviated, time: .omitted)
        let endStr = end.formatted(date: .abbreviated, time: .omitted)
        return "\(startStr) – \(endStr)"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(rangeText)
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
                Spacer()
                Text(summary.averagePaceString)
                    .font(.subheadline)
                    .foregroundColor(.taqvoAccentText)
            }

            HStack {
                VStack(alignment: .leading) {
                    Text("Total Distance")
                        .font(.caption)
                        .foregroundColor(.taqvoAccentText)
                    Text(String(format: "%.2f km", summary.totalDistanceMeters/1000.0))
                        .font(.title3)
                        .foregroundColor(.taqvoTextDark)
                }
                Spacer()
                VStack(alignment: .trailing) {
                    Text("Total Time")
                        .font(.caption)
                        .foregroundColor(.taqvoAccentText)
                    Text(ActivityTrackingViewModel.formattedDuration(summary.totalDurationSeconds))
                        .font(.title3)
                        .foregroundColor(.taqvoTextDark)
                }
            }

            HStack {
                Text("Longest Run")
                    .font(.caption)
                    .foregroundColor(.taqvoAccentText)
                Spacer()
                Text(String(format: "%.2f km", summary.longestRunMeters/1000.0))
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
                Text(" • ")
                    .foregroundColor(.taqvoAccentText)
                Text(ActivityTrackingViewModel.formattedDuration(summary.longestRunDurationSeconds))
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
            }
        }
        .padding(.vertical, 8)
    }
}

struct ProfileView: View {
    var body: some View {
        NavigationStack {
            VStack(spacing: 16) {
                Text("Profile")
                    .font(.title)
                    .foregroundColor(.taqvoTextDark)
                Text("Integrations and privacy settings")
                    .foregroundColor(.taqvoAccentText)
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color.taqvoBackgroundDark)
            .navigationTitle("Profile")
        }
    }
}

#Preview {
    MainTabView()
}

struct DailySummaryCard: View {
    let summary: DailySummary

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(summary.dayStart.formatted(date: .abbreviated, time: .omitted))
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
                Spacer()
                Text(summary.averagePaceString)
                    .font(.subheadline)
                    .foregroundColor(.taqvoAccentText)
            }

            HStack {
                VStack(alignment: .leading) {
                    Text("Total Distance")
                        .font(.caption)
                        .foregroundColor(.taqvoAccentText)
                    Text(String(format: "%.2f km", summary.totalDistanceMeters/1000.0))
                        .font(.title3)
                        .foregroundColor(.taqvoTextDark)
                }
                Spacer()
                VStack(alignment: .trailing) {
                    Text("Total Time")
                        .font(.caption)
                        .foregroundColor(.taqvoAccentText)
                    Text(ActivityTrackingViewModel.formattedDuration(summary.totalDurationSeconds))
                        .font(.title3)
                        .foregroundColor(.taqvoTextDark)
                }
            }

            HStack {
                Text("Runs")
                    .font(.caption)
                    .foregroundColor(.taqvoAccentText)
                Spacer()
                Text("\(summary.runCount)")
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
                Text(" • ")
                    .foregroundColor(.taqvoAccentText)
                Text("Longest \(String(format: "%.2f km", summary.longestRunMeters/1000.0))")
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
            }
        }
        .padding(.vertical, 8)
    }
}

struct MonthlySummaryCard: View {
    let summary: MonthlySummary

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(summary.monthStart.formatted(.dateTime.month(.abbreviated).year()))
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
                Spacer()
                Text(summary.averagePaceString)
                    .font(.subheadline)
                    .foregroundColor(.taqvoAccentText)
            }

            HStack {
                VStack(alignment: .leading) {
                    Text("Total Distance")
                        .font(.caption)
                        .foregroundColor(.taqvoAccentText)
                    Text(String(format: "%.2f km", summary.totalDistanceMeters/1000.0))
                        .font(.title3)
                        .foregroundColor(.taqvoTextDark)
                }
                Spacer()
                VStack(alignment: .trailing) {
                    Text("Total Time")
                        .font(.caption)
                        .foregroundColor(.taqvoAccentText)
                    Text(ActivityTrackingViewModel.formattedDuration(summary.totalDurationSeconds))
                        .font(.title3)
                        .foregroundColor(.taqvoTextDark)
                }
            }

            HStack {
                Text("Runs")
                    .font(.caption)
                    .foregroundColor(.taqvoAccentText)
                Spacer()
                Text("\(summary.runCount)")
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
                Text(" • ")
                    .foregroundColor(.taqvoAccentText)
                Text("Longest \(String(format: "%.2f km", summary.longestRunMeters/1000.0))")
                    .font(.headline)
                    .foregroundColor(.taqvoTextDark)
            }
        }
        .padding(.vertical, 8)
    }
}