//
//  MapRouteView.swift
//  Taqvo
//
//  Generated by Assistant on 10/17/25
//

import SwiftUI
import MapKit

struct MapRouteView: UIViewRepresentable {
    var route: [CLLocationCoordinate2D]

    class Coordinator: NSObject, MKMapViewDelegate {
        func mapView(_ mapView: MKMapView, rendererFor overlay: MKOverlay) -> MKOverlayRenderer {
            if let polyline = overlay as? MKPolyline {
                let r = MKPolylineRenderer(polyline: polyline)
                r.strokeColor = .systemGreen
                r.lineWidth = 4
                return r
            }
            return MKOverlayRenderer(overlay: overlay)
        }
    }

    func makeCoordinator() -> Coordinator { Coordinator() }

    func makeUIView(context: Context) -> MKMapView {
        let map = MKMapView()
        map.delegate = context.coordinator
        map.showsUserLocation = true
        map.isPitchEnabled = true
        map.isRotateEnabled = false
        map.overrideUserInterfaceStyle = .dark
        return map
    }

    func updateUIView(_ map: MKMapView, context: Context) {
        // Avoid CAMetalLayer warnings when the view hasn't been sized yet.
        guard map.bounds.width > 0 && map.bounds.height > 0 else { return }

        map.removeOverlays(map.overlays)
        if route.count > 1 {
            let polyline = MKPolyline(coordinates: route, count: route.count)
            map.addOverlay(polyline)
            let region = MKCoordinateRegion(polyline.boundingMapRect)
            map.setRegion(regionThatFits(region: region, paddingScale: 1.2), animated: true)
        } else if let last = route.last {
            let region = MKCoordinateRegion(center: last, latitudinalMeters: 800, longitudinalMeters: 800)
            map.setRegion(region, animated: true)
        }
    }

    private func regionThatFits(region: MKCoordinateRegion, paddingScale: Double) -> MKCoordinateRegion {
        MKCoordinateRegion(center: region.center,
                           span: MKCoordinateSpan(latitudeDelta: region.span.latitudeDelta * paddingScale,
                                                   longitudeDelta: region.span.longitudeDelta * paddingScale))
    }
}