//
//  RootView.swift
//  Taqvo
//
//  Generated by Assistant on 10/17/25
//

import SwiftUI

struct RootView: View {
    @EnvironmentObject var appState: AppState
    @AppStorage("appTheme") private var appTheme: String = "system"

    private var preferredScheme: ColorScheme? {
        switch appTheme {
        case "dark": return .dark
        case "light": return .light
        default: return nil
        }
    }

    var body: some View {
        Group {
            if appState.hasCompletedOnboarding {
                MainTabView()
            } else {
                OnboardingView()
            }
        }
        .preferredColorScheme(preferredScheme)
        .onOpenURL { url in
            SpotifyAuthManager.shared.handleCallbackURL(url)
        }
    }
}

#Preview {
    RootView()
        .environmentObject(AppState())
}