//
//  RootView.swift
//  Taqvo
//
//  Generated by Assistant on 10/17/25
//

import SwiftUI

struct RootView: View {
    @EnvironmentObject var appState: AppState

    var body: some View {
        Group {
            if appState.hasCompletedOnboarding {
                MainTabView()
            } else {
                OnboardingView()
            }
        }
        .preferredColorScheme(.dark)
        .onOpenURL { url in
            SpotifyAuthManager.shared.handleCallbackURL(url)
        }
    }
}

#Preview {
    RootView()
        .environmentObject(AppState())
}